    await page.getByRole('textbox', { name: 'Username' }).click();
    await page.getByRole('textbox', { name: 'Username' }).fill('testuser');
    await page.getByRole('textbox', { name: 'Password' }).dblclick();
    await page.getByRole('textbox', { name: 'Password' }).fill('testuser123#');
    await page.getByRole('button', { name: 'Sign in' }).click();
    await page.getByText('Demo Store', { exact: true }).click();
    await page.getByRole('textbox', { name: 'Search for products...' }).click();
    await page.getByRole('textbox', { name: 'Search for products...' }).fill('iphone');
    await page.getByRole('button', { name: 'Search' }).click();
    await page.getByRole('textbox', { name: 'Search for products...' }).dblclick();
    await page.getByText('No products found').click();
    await page.getByRole('heading', { name: 'Products' }).click();
    await page.getByRole('textbox', { name: 'Search for products...' }).dblclick();
    await page.getByRole('button', { name: 'Sign in' }).click();
    await page.getByText('Premium Wireless Headphones $').click();
    await page.getByRole('heading', { name: 'Products' }).click();
    await page.locator('.product-card > .p-4 > .flex').first().click();
    await page.getByRole('heading', { name: 'Premium Wireless Headphones' }).click();
    await page.getByText('$199.99').click();
    await page.getByRole('button', { name: 'View cart' }).click();
    await page.getByRole('heading', { name: 'Your Cart' }).click();
    await page.getByText('Your cart is empty').click();
    await page.getByText('0.00').click();
    await page.getByText('Total: $').click();
    await page.getByRole('button', { name: 'Checkout' }).click();
    await page.locator('#close-cart').click();
    await page.getByText('Welcome, Test User').click();
    await page.getByRole('button', { name: 'Add to Cart' }).first().click();
    await page.getByRole('button', { name: 'View cart' }).click();
    await page.locator('h4').click();
    await page.getByText('$199.99 x').click();
    await page.locator('#cart-modal').getByText('$199.99', { exact: true }).click();
    await page.getByText('199.99', { exact: true }).click();
    await page.getByText('Total: $').click();
    await page.getByRole('button', { name: 'Checkout' }).click();
    await page.locator('#close-cart').click();fill('[data-testid="username"]', 'testuser');
    await page.fill('[data-testid="password"]', 'testuser123#');